# Generated by Django 4.1.7 on 2023-03-30 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_alter_order_status_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Очікує на розгляд', 'Очікує на розгляд'), ('Прийнят', 'Прийнят'), ('Упакований', 'Упакований'), ('На шляху', 'На шляху'), ('Доставлено', 'Доставлено'), ('Скасовано', 'Скасовано')], default='Очікує на розгляд', max_length=50),
        ),
        migrations.CreateModel(
            name='PayingWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, verbose_name='card_number')),
                ('CVV', models.CharField(max_length=3, verbose_name='CVV')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
