# Generated by Django 3.2.3 on 2023-05-26 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_paying_way'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_uk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Category Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Category Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Category Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='Category Title'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.address', verbose_name='Shipping Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_uk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.address', verbose_name='Shipping Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_uk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_en',
            field=models.CharField(choices=[('Очікує на розгляд', 'Очікує на розгляд'), ('Прийнят', 'Прийнят'), ('Упакований', 'Упакований'), ('На шляху', 'На шляху'), ('Доставлено', 'Доставлено'), ('Скасовано', 'Скасовано')], default='Очікує на розгляд', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_uk',
            field=models.CharField(choices=[('Очікує на розгляд', 'Очікує на розгляд'), ('Прийнят', 'Прийнят'), ('Упакований', 'Упакований'), ('На шляху', 'На шляху'), ('Доставлено', 'Доставлено'), ('Скасовано', 'Скасовано')], default='Очікує на розгляд', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Product Categoy'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_uk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Product Categoy'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Detail Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Detail Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_uk',
            field=models.TextField(null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Product Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uk',
            field=models.CharField(max_length=150, null=True, verbose_name='Product Title'),
        ),
    ]
