# Generated by Django 3.2.3 on 2023-05-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20230526_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_uk',
            new_name='product_ru',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description_uk',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title_uk',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_uk',
            new_name='address_ru',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_uk',
            new_name='product_ru',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status_uk',
            new_name='status_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_uk',
            new_name='category_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='detail_description_uk',
            new_name='detail_description_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='short_description_uk',
            new_name='short_description_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_uk',
            new_name='title_ru',
        ),
    ]
