# Generated by Django 3.2.3 on 2023-05-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20230529_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_en',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_uk',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_en',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_uk',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_uk',
        ),
    ]
